name: musicparty

services:
  musicparty:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=musicparty
      - XDEBUG_MODE=debug
      - XDEBUG_SESSION=start
      - CADDY_SERVER_FRANKENPHP_OPTIONS=
      - APP_INDEX_FILE=index.php
    ports:
      - "9000:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  reverb:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: [ "php", "artisan", "reverb:start", "--host=0.0.0.0", "--debug", "--port=80" ]
    healthcheck:
      disable: true

  horizon:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    restart: unless-stopped
    entrypoint: [ "php", "artisan", "horizon" ]
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      disable: true

  scheduler:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    restart: unless-stopped
    entrypoint: [ "php", "artisan", "schedule:work" ]
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      disable: true

  db:
    image: mariadb:10.5-focal
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6.2.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  composer:
    profiles: [ "composer" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "composer" ]
    command: [ "--version" ]
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - ./:/app
    healthcheck:
      disable: true

  test:
    profiles: [ "test" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "php", "vendor/bin/phpunit" ]
    volumes:
      - ./:/app
    healthcheck:
      disable: true

  npm:
    profiles: [ "npm" ]
    image: node:23
    entrypoint: [ "npm" ]
    command: [ "" ]
    working_dir: /app
    user: node
    volumes:
      - ./:/app

  artisan:
    profiles: [ "artisan" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "php", "/app/artisan" ]
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      disable: true

  phpcs:
    profiles: [ "phpcs" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "vendor/bin/phpcs" ]
    volumes:
      - ./:/app/
    healthcheck:
      disable: true

  phpcbf:
    profiles: [ "phpcbf" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "vendor/bin/phpcbf" ]
    volumes:
      - ./:/app/
    healthcheck:
      disable: true

  shell:
    profiles: [ "shell" ]
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    entrypoint: [ "/bin/sh" ]
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      disable: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 50M
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
    driver: local
