# https://taskfile.dev

version: "3"

tasks:
  default:
    silent: true

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  image-build:
    cmds:
      - docker compose build

  composer:
    cmds:
      - docker compose run -it --rm composer {{.CLI_ARGS}}

  composer-install:
    cmds:
      - docker compose run -it --rm composer install

  composer-update:
    cmds:
      - docker compose run -it --rm composer update

  npm:
    cmds:
      - docker compose run -it --rm npm {{.CLI_ARGS}}

  npm-install:
    cmds:
      - docker compose run -it --rm npm install

  npm-update:
    cmds:
      - docker compose run -it --rm npm update

  watch:
    cmds:
      - docker compose run -it --rm -p 5173:5173 npm run dev

  build:
    cmds:
      - docker compose run -it --rm npm run build

  migrate:
    cmds:
      - docker compose run --rm artisan migrate

  seed:
    cmds:
      - docker compose run --rm artisan db:seed

  setup:
    cmds:
      - docker compose up -d redis db
      - task: composer-install
      - docker compose run --rm artisan key:generate
      - task: migrate
      - task: seed
      - docker compose run --rm artisan setup:discord
      - task: npm-install
      - task: build
      - docker compose down
